version: '3.9'
services:
  guitar-shop.mongo:
    image: mongo:4.4
    restart: always
    container_name: guitar-shop.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: guitar-shop

    ports:
      - :27017:27017

    volumes:
      - guitar-shop.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/guitar-shop --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  guitar-shop.mongo.ui:
    image: mongo-express
    restart: always
    container_name: guitar-shop.mongo.ui
    ports:
      - :8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@guitar-shop.mongo:27017/

  guitar-shop.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "guitar-shop.notify.fakesmtp"
    hostname: "guitar-shop.notify.fakesmtp"
    ports:
      - "8025:8025"
      - "1083:8080"

volumes:
  guitar-shop.mongo:

